# Generated by Django 6.0.4 on 2026-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deposit_address',
            field=models.CharField(default='0x71C7656EC7ab88b098defB751B7401B5f6d8976F', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_id_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_id_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
