# Generated by Django 6.0.4 on 2026-04-10 13:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asset_deposit_address_transaction_receipt_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
