# Generated by Django 6.0.4 on 2026-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_usd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='network',
            field=models.CharField(default='ERC20', max_length=50),
        ),
    ]
