# Generated by Django 6.0.4 on 2026-04-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_remark_userprofile_active_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
