# Generated by Django 6.0.4 on 2026-04-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asset_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Total ban. Cannot login.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Restricted access. Forced to suspend page.'),
        ),
    ]
