# Generated by Django 6.0.4 on 2026-04-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_is_blocked_userprofile_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_managed',
            field=models.BooleanField(default=False, help_text='Executed by broker/AI'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='message',
            field=models.TextField(blank=True, help_text='Instructions for the trader'),
        ),
    ]
