# Generated by Django 6.0.4 on 2026-04-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_is_managed_tradingsignal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
