# Generated by Django 6.0.4 on 2026-04-13 12:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaction_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_demo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_demo_mode',
            field=models.BooleanField(default=True, help_text='Switch between Demo and Real trading'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='demo_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=30),
        ),
    ]
