# Generated by Django 6.0.4 on 2026-04-13 20:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_managedtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedtrade',
            name='entry_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='managedtrade',
            name='trade_action',
            field=models.CharField(choices=[('BUY', 'Buy (Long)'), ('SELL', 'Sell (Short)')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='managedtrade',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in USDT', max_digits=30),
        ),
        migrations.AlterField(
            model_name='managedtrade',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit in USDT', max_digits=30),
        ),
    ]
